import {
  GiCardAceClubs,
  GiCard2Clubs,
  GiCard3Clubs,
  GiCard4Clubs,
  GiCard5Clubs,
  GiCard6Clubs,
  GiCard7Clubs,
  GiCard8Clubs,
  GiCard9Clubs,
  GiCard10Clubs,
  GiCardJackClubs,
  GiCardQueenClubs,
  GiCardKingClubs,
  GiCardAceDiamonds,
  GiCard2Diamonds,
  GiCard3Diamonds,
  GiCard4Diamonds,
  GiCard5Diamonds,
  GiCard6Diamonds,
  GiCard7Diamonds,
  GiCard8Diamonds,
  GiCard9Diamonds,
  GiCard10Diamonds,
  GiCardJackDiamonds,
  GiCardQueenDiamonds,
  GiCardKingDiamonds,
  // GiCardJackDiamonds,
  // GiCardKingDiamonds,
  GiCardAceHearts,
  GiCard2Hearts,
  GiCard3Hearts,
  GiCard4Hearts,
  GiCard5Hearts,
  GiCard6Hearts,
  GiCard7Hearts,
  GiCard8Hearts,
  GiCard9Hearts,
  GiCard10Hearts,
  GiCardJackHearts,
  GiCardQueenHearts,
  GiCardKingHearts,
  // GiCardQueenHearts,
  GiCard10Spades,
  GiCard8Spades
} from "react-icons/gi";

const cardMap = {
  'AC': GiCardAceClubs,
  '2C': GiCard2Clubs,
  '3C': GiCard3Clubs,
  '4C': GiCard4Clubs,
  '5C': GiCard5Clubs,
  '6C': GiCard6Clubs,
  '7C': GiCard7Clubs,
  '8C': GiCard8Clubs,
  '9C': GiCard9Clubs,
  '10C': GiCard10Clubs,
  'JC': GiCardJackClubs,
  'QC': GiCardQueenClubs,
  'KC': GiCardKingClubs,
  'AD': GiCardAceDiamonds,
  '2D': GiCard2Diamonds,
  '3D': GiCard3Diamonds,
  '4D': GiCard4Diamonds,
  '5D': GiCard5Diamonds,
  '6D': GiCard6Diamonds,
  '7D': GiCard7Diamonds,
  '8D': GiCard8Diamonds,
  '9D': GiCard9Diamonds,
  '10D': GiCard10Diamonds,
  'JD': GiCardJackDiamonds,
  'QD': GiCardQueenDiamonds,
  'KD': GiCardKingDiamonds,
  // 'JD': GiCardJackDiamonds,
  // 'KD': GiCardKingDiamonds,
  'AH': GiCardAceHearts,
  '2H': GiCard2Hearts,
  '3H': GiCard3Hearts,
  '4H': GiCard4Hearts,
  '5H': GiCard5Hearts,
  '6H': GiCard6Hearts,
  '7H': GiCard7Hearts,
  '8H': GiCard8Hearts,
  '9H': GiCard9Hearts,
  '10H': GiCard10Hearts,
  'JH': GiCardJackHearts,
  'QH': GiCardQueenHearts,
  'KH': GiCardKingHearts,
  // 'QH': GiCardQueenHearts,
  '8S': GiCard8Spades,
  '10S': GiCard10Spades,
}

export default cardMap